<a href="https://colab.research.google.com/github/Malavika-2211/fds-experiments-250701409/blob/main/exp_10).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# EXP NO. 10
# UNDERSTANDING ARRAY FUNCTIONS USING NUMPY

import numpy as np

# 1. CREATING ARRAYS

ARR1 = np.array([10, 20, 30, 40, 50])

print("ARRAY 1:")
print(ARR1)

# 2D ARRAY
ARR2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\n2D ARRAY:")
print(ARR2)


# 2. ARRAY PROPERTIES

print("\nARRAY PROPERTIES:")
print("DIMENSIONS:", ARR2.ndim)
print("SHAPE:", ARR2.shape)
print("SIZE:", ARR2.size)
print("DATA TYPE:", ARR2.dtype)


# 3. SPECIAL ARRAY FUNCTIONS

print("\nZEROS ARRAY:")
print(np.zeros((2, 3)))

print("\nONES ARRAY:")
print(np.ones((2, 3)))

print("\nIDENTITY MATRIX:")
print(np.eye(3))

print("\nARRAY USING ARANGE:")
print(np.arange(1, 11))

print("\nARRAY USING LINSPACE:")
print(np.linspace(0, 10, 5))


# 4. RESHAPING AN ARRAY

ARR3 = np.arange(1, 10)

print("\nORIGINAL ARRAY:")
print(ARR3)

RESHAPED = ARR3.reshape(3, 3)

print("\nRESHAPED ARRAY:")
print(RESHAPED)


# 5. MATHEMATICAL OPERATIONS

A = np.array([10, 20, 30, 40])
B = np.array([1, 2, 3, 4])

print("\nARRAY ADDITION:")
print(A + B)

print("\nARRAY SUBTRACTION:")
print(A - B)

print("\nARRAY MULTIPLICATION:")
print(A * B)

print("\nARRAY DIVISION:")
print(A / B)


# 6. AGGREGATE FUNCTIONS

NUMBERS = np.array([10, 20, 30, 40, 50])

print("\nSUM:", np.sum(NUMBERS))
print("MEAN:", np.mean(NUMBERS))
print("MEDIAN:", np.median(NUMBERS))
print("MAXIMUM:", np.max(NUMBERS))
print("MINIMUM:", np.min(NUMBERS))
print("STANDARD DEVIATION:", np.std(NUMBERS))


# 7. ARRAY INDEXING AND SLICING

print("\nFIRST ELEMENT:")
print(NUMBERS[0])

print("\nLAST ELEMENT:")
print(NUMBERS[-1])

print("\nFIRST THREE ELEMENTS:")
print(NUMBERS[:3])

print("\nELEMENTS FROM INDEX 2:")
print(NUMBERS[2:])


# 8. SORTING AN ARRAY

UNSORTED = np.array([50, 20, 40, 10, 30])

print("\nUNSORTED ARRAY:")
print(UNSORTED)

print("\nSORTED ARRAY:")
print(np.sort(UNSORTED))


# 9. CONCATENATING ARRAYS

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

print("\nCONCATENATED ARRAY:")
print(np.concatenate((X, Y)))


# 10. FINDING UNIQUE VALUES

DATA = np.array([1, 2, 2, 3, 3, 3, 4, 5])

print("\nUNIQUE VALUES:")
print(np.unique(DATA))

ARRAY 1:
[10 20 30 40 50]

2D ARRAY:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

ARRAY PROPERTIES:
DIMENSIONS: 2
SHAPE: (3, 3)
SIZE: 9
DATA TYPE: int64

ZEROS ARRAY:
[[0. 0. 0.]
 [0. 0. 0.]]

ONES ARRAY:
[[1. 1. 1.]
 [1. 1. 1.]]

IDENTITY MATRIX:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

ARRAY USING ARANGE:
[ 1  2  3  4  5  6  7  8  9 10]

ARRAY USING LINSPACE:
[ 0.   2.5  5.   7.5 10. ]

ORIGINAL ARRAY:
[1 2 3 4 5 6 7 8 9]

RESHAPED ARRAY:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

ARRAY ADDITION:
[11 22 33 44]

ARRAY SUBTRACTION:
[ 9 18 27 36]

ARRAY MULTIPLICATION:
[ 10  40  90 160]

ARRAY DIVISION:
[10. 10. 10. 10.]

SUM: 150
MEAN: 30.0
MEDIAN: 30.0
MAXIMUM: 50
MINIMUM: 10
STANDARD DEVIATION: 14.142135623730951

FIRST ELEMENT:
10

LAST ELEMENT:
50

FIRST THREE ELEMENTS:
[10 20 30]

ELEMENTS FROM INDEX 2:
[30 40 50]

UNSORTED ARRAY:
[50 20 40 10 30]

SORTED ARRAY:
[10 20 30 40 50]

CONCATENATED ARRAY:
[1 2 3 4 5 6]

UNIQUE VALUES:
[1 2 3 4 5]
